# Form implementation generated from reading ui file 'c:\Git\DP\DP-QtDesktopApp\UIs\ControlTab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ControlTab(object):
    def setupUi(self, ControlTab):
        ControlTab.setObjectName("ControlTab")
        ControlTab.resize(1034, 827)
        self.pushButton = QtWidgets.QPushButton(parent=ControlTab)
        self.pushButton.setGeometry(QtCore.QRect(40, 220, 131, 24))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=ControlTab)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 270, 501, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vLayoutMeasuring_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vLayoutMeasuring_2.setContentsMargins(0, 0, 0, 0)
        self.vLayoutMeasuring_2.setObjectName("vLayoutMeasuring_2")
        self.labelMeasuring_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelMeasuring_2.setObjectName("labelMeasuring_2")
        self.vLayoutMeasuring_2.addWidget(self.labelMeasuring_2)
        self.textEditMeasuring_2 = QtWidgets.QTextEdit(parent=self.layoutWidget)
        self.textEditMeasuring_2.setReadOnly(True)
        self.textEditMeasuring_2.setObjectName("textEditMeasuring_2")
        self.vLayoutMeasuring_2.addWidget(self.textEditMeasuring_2)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=ControlTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(510, 50, 501, 95))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.vLayoutMeasuring_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.vLayoutMeasuring_3.setContentsMargins(0, 0, 0, 0)
        self.vLayoutMeasuring_3.setObjectName("vLayoutMeasuring_3")
        self.labelMeasuring_3 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.labelMeasuring_3.setObjectName("labelMeasuring_3")
        self.vLayoutMeasuring_3.addWidget(self.labelMeasuring_3)
        self.textEditMeasuring_3 = QtWidgets.QTextEdit(parent=self.layoutWidget_2)
        self.textEditMeasuring_3.setReadOnly(True)
        self.textEditMeasuring_3.setObjectName("textEditMeasuring_3")
        self.vLayoutMeasuring_3.addWidget(self.textEditMeasuring_3)
        self.labelTitle = QtWidgets.QLabel(parent=ControlTab)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 1178, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.pushButton_2 = QtWidgets.QPushButton(parent=ControlTab)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 250, 131, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=ControlTab)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 280, 131, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(parent=ControlTab)
        self.widget.setGeometry(QtCore.QRect(510, 160, 501, 95))
        self.widget.setObjectName("widget")
        self.vLayoutMeasuring = QtWidgets.QVBoxLayout(self.widget)
        self.vLayoutMeasuring.setContentsMargins(0, 0, 0, 0)
        self.vLayoutMeasuring.setObjectName("vLayoutMeasuring")
        self.labelMeasuring = QtWidgets.QLabel(parent=self.widget)
        self.labelMeasuring.setObjectName("labelMeasuring")
        self.vLayoutMeasuring.addWidget(self.labelMeasuring)
        self.textEditMeasuring = QtWidgets.QTextEdit(parent=self.widget)
        self.textEditMeasuring.setReadOnly(True)
        self.textEditMeasuring.setObjectName("textEditMeasuring")
        self.vLayoutMeasuring.addWidget(self.textEditMeasuring)

        self.retranslateUi(ControlTab)
        QtCore.QMetaObject.connectSlotsByName(ControlTab)

    def retranslateUi(self, ControlTab):
        _translate = QtCore.QCoreApplication.translate
        ControlTab.setWindowTitle(_translate("ControlTab", "Form"))
        self.pushButton.setText(_translate("ControlTab", "Spustit měření napětí"))
        self.labelMeasuring_2.setText(_translate("ControlTab", "Stav databáze"))
        self.textEditMeasuring_2.setPlaceholderText(_translate("ControlTab", "Nepřipojena"))
        self.labelMeasuring_3.setText(_translate("ControlTab", "Stav konfigurace testované DPS"))
        self.textEditMeasuring_3.setPlaceholderText(_translate("ControlTab", "Nezvolena"))
        self.labelTitle.setText(_translate("ControlTab", "Hlavní ovládací panel"))
        self.pushButton_2.setText(_translate("ControlTab", "Spustit test RS-485"))
        self.pushButton_3.setText(_translate("ControlTab", "Spustit test DI/DO"))
        self.labelMeasuring.setText(_translate("ControlTab", "Stav měření"))
        self.textEditMeasuring.setPlaceholderText(_translate("ControlTab", "Nespuštěno"))
