# Form implementation generated from reading ui file 'c:\Users\xstejs30\Documents\PythonProjects\PyWinApp\main\DP\UIs\ConfigurationTab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfigurationTab(object):
    def setupUi(self, ConfigurationTab):
        ConfigurationTab.setObjectName("ConfigurationTab")
        ConfigurationTab.resize(450, 450)
        ConfigurationTab.setMinimumSize(QtCore.QSize(450, 450))
        ConfigurationTab.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Czech, QtCore.QLocale.Country.Czechia))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConfigurationTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(parent=ConfigurationTab)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeSpec.UTC)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 1)
        self.textEditJobDesc = QtWidgets.QTextEdit(parent=ConfigurationTab)
        self.textEditJobDesc.setMinimumSize(QtCore.QSize(100, 0))
        self.textEditJobDesc.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEditJobDesc.setObjectName("textEditJobDesc")
        self.gridLayout.addWidget(self.textEditJobDesc, 4, 1, 1, 1)
        self.employeeName = QtWidgets.QLabel(parent=ConfigurationTab)
        self.employeeName.setObjectName("employeeName")
        self.gridLayout.addWidget(self.employeeName, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=ConfigurationTab)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setMaxLength(40)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.department = QtWidgets.QLabel(parent=ConfigurationTab)
        self.department.setObjectName("department")
        self.gridLayout.addWidget(self.department, 1, 0, 1, 1)
        self.employmentDate_2 = QtWidgets.QLabel(parent=ConfigurationTab)
        self.employmentDate_2.setObjectName("employmentDate_2")
        self.gridLayout.addWidget(self.employmentDate_2, 3, 0, 1, 1)
        self.jobDescription = QtWidgets.QLabel(parent=ConfigurationTab)
        self.jobDescription.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.jobDescription.setObjectName("jobDescription")
        self.gridLayout.addWidget(self.jobDescription, 4, 0, 1, 1)
        self.employmentDate = QtWidgets.QLabel(parent=ConfigurationTab)
        self.employmentDate.setObjectName("employmentDate")
        self.gridLayout.addWidget(self.employmentDate, 2, 0, 1, 1)
        self.comboBoxDept_2 = QtWidgets.QComboBox(parent=ConfigurationTab)
        self.comboBoxDept_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxDept_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBoxDept_2.setEditable(True)
        self.comboBoxDept_2.setMaxCount(10)
        self.comboBoxDept_2.setObjectName("comboBoxDept_2")
        self.gridLayout.addWidget(self.comboBoxDept_2, 0, 1, 1, 1)
        self.doubleSpinBoxSalary_2 = QtWidgets.QDoubleSpinBox(parent=ConfigurationTab)
        self.doubleSpinBoxSalary_2.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSalary_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSalary_2.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.doubleSpinBoxSalary_2.setDecimals(1)
        self.doubleSpinBoxSalary_2.setSingleStep(0.1)
        self.doubleSpinBoxSalary_2.setObjectName("doubleSpinBoxSalary_2")
        self.gridLayout.addWidget(self.doubleSpinBoxSalary_2, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConfigurationTab)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.employeeName.setBuddy(self.comboBoxDept_2)
        self.department.setBuddy(self.lineEdit)
        self.employmentDate_2.setBuddy(self.dateEdit)
        self.jobDescription.setBuddy(self.textEditJobDesc)
        self.employmentDate.setBuddy(self.doubleSpinBoxSalary_2)

        self.retranslateUi(ConfigurationTab)
        self.buttonBox.clicked['QAbstractButton*'].connect(self.comboBoxDept_2.clear) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(self.comboBoxDept_2.clearEditText) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(self.lineEdit.clear) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(self.doubleSpinBoxSalary_2.clear) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(self.dateEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfigurationTab)
        ConfigurationTab.setTabOrder(self.comboBoxDept_2, self.lineEdit)
        ConfigurationTab.setTabOrder(self.lineEdit, self.doubleSpinBoxSalary_2)
        ConfigurationTab.setTabOrder(self.doubleSpinBoxSalary_2, self.dateEdit)
        ConfigurationTab.setTabOrder(self.dateEdit, self.textEditJobDesc)

    def retranslateUi(self, ConfigurationTab):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationTab.setWindowTitle(_translate("ConfigurationTab", "Form"))
        self.dateEdit.setDisplayFormat(_translate("ConfigurationTab", "dd. MM. yyyy"))
        self.employeeName.setText(_translate("ConfigurationTab", "&Název konfigurace:"))
        self.department.setText(_translate("ConfigurationTab", "Jméno &authora:"))
        self.employmentDate_2.setText(_translate("ConfigurationTab", "&Datum konfigurace:"))
        self.jobDescription.setText(_translate("ConfigurationTab", "&Popis konfigurace"))
        self.employmentDate.setText(_translate("ConfigurationTab", "&Verze konfigurace:"))
        self.doubleSpinBoxSalary_2.setPrefix(_translate("ConfigurationTab", "v"))
